"""Add llm_debug field to messages table

Revision ID: 004
Revises: 003
Create Date: 2025-12-05 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite, postgresql


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加llm_debug字段到messages表
    # 对于SQLite，我们需要先添加列为JSON类型（SQLite将JSON存储为TEXT）
    # 对于PostgreSQL，我们可以使用JSON类型
    try:
        # 尝试使用PostgreSQL的JSON类型
        op.add_column('messages', sa.Column('llm_debug', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    except:
        # 如果PostgreSQL不可用，使用通用的JSON类型（会降级到TEXT）
        op.add_column('messages', sa.Column('llm_debug', sa.JSON(), nullable=True))

    # 添加updated_at字段（如果不存在）
    try:
        op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    except:
        # 如果列已存在，忽略错误
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除llm_debug字段
    try:
        op.drop_column('messages', 'llm_debug')
    except:
        # 如果列不存在，忽略错误
        pass

    # 删除updated_at字段
    try:
        op.drop_column('messages', 'updated_at')
    except:
        # 如果列不存在，忽略错误
        pass
    # ### end Alembic commands ###