"""Extend topic field length from 200 to 2000 characters

Revision ID: 005
Revises: 004
Create Date: 2025-12-07 14:46:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'topic',
                    existing_type=sa.String(length=200),
                    type_=sa.String(length=2000),
                    existing_nullable=False)
    op.alter_column('flow_templates', 'topic',
                    existing_type=sa.String(length=200),
                    type_=sa.String(length=2000),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_templates', 'topic',
                    existing_type=sa.String(length=2000),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('sessions', 'topic',
                    existing_type=sa.String(length=2000),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    # ### end Alembic commands ###